name: Build Kura
on:
  push:
    branches: [main]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run vcpkg Setup
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgGitCommitId: 'aa40adda5352e87655b8583cfb2451d5e9e276fd'
        env:
          # Instructs vcpkg to use the exported GitHub Actions cache variables
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      - name: Install llvm
        run: |
          sudo apt-get update
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" -- 22
      - name: Configure CMake
        run: |
          cmake --preset=clang-debug .
      - name: Build kura
        run: cmake --build build
