name: Build Kura
on:
  push:
    branches: [main]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install llvm
        run: |
          sudo apt-get update
          # Download and run the official LLVM installation script for version 22
          wget https://llvm.org
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          # Install extra development packages if needed (optional)
          sudo apt-get install -y libclang-22-dev llvm-22-dev
      - name: Configure CMake
        run: |
          cmake --preset=clang-debug .
      - name: Build kura
        run: cmake --build build
